# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6aaf2c74b952e64c21b8f5a6615c28e47cb96b972db629f50752c94382a20dbcf7ebceaae1023dfac2a3225914f144ede4084742415e82ad3b5451941147ddea

test:
  secret_key_base: 6ea258322645349f64782c9e6f49802375dc69ec9428bf40ec2de3a5c62a78522d281b58051b9b4771cce5c763a2e2791003d6b59191c9b590fe63254b47403d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 6ea258322645349f64782c9e6f49802375dc69ec9428bf40ec2de3a5c62a78522d281b58051b9b4771cce5c763a2e2791003d6b59191c9b590fe63254b47403d
